spring:
  datasource:
    url: jdbc:ignite:thin://127.0.0.1/PUBLIC
    username: ignite
    password: ignite
    driverClassName: org.apache.ignite.IgniteJdbcThinDriver
  jpa:
    database: H2
    show-sql: true
  liquibase:
    enabled: false

logging:
  level:
    org:
      jooq: DEBUG
