server:
  port: ${PORT:8080}
  error:
    include-message: always
    include-exception: true
    whitelabel:
      enabled: false

spring:
  jpa:
    show-sql: true
  liquibase:
    change-log: db/changelog/changelog.xml

springdoc:
  swagger-ui:
    path: /docs
    groups-order: asc
    operations-sorter: method
    supported-submit-methods: ['get', 'post', 'put', 'delete']
  api-docs:
    path: /api-docs
  use-fqn: true
